### ISSUE TITLE
Error running mosdepth

### ISSUE THREAD

**Issue by kokyriakidis** [brentp/mosdepth#99]
I got this error on mosdepth step:
```
[2019-12-18T17:20Z] multiprocessing: postprocess_alignment
[2019-12-18T17:20Z] Calculating coverage: KONSTANTINOS variant_regions
[2019-12-18T17:20Z] fatal.nim(39)            sysFatal
[2019-12-18T17:20Z] Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	212419319	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
[2019-12-18T17:20Z] A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
[2019-12-18T17:20Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 19 -F 1804 -Q 1 --no-per-base --by /media/kokyriakidis/REDPRO/work/coverage/KONSTANTINOS/target-genome.bed --quantize 0:1:4: /media/kokyriakidis/REDPRO/work/bcbiotx/tmp_0u74h5t/KONSTANTINOS-variant_regions /media/kokyriakidis/REDPRO/work/align/KONSTANTINOS/KONSTANTINOS-sort.bam 
fatal.nim(39)            sysFatal
Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	2124193	19	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 153, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 256, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/callable.py", line 45, in sample_callable_bed
    callable_bed, depth_files = coverage.calculate(bam_file, data, sv_bed)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 100, in calculate
    per_base=per_base)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 238, in run_mosdepth
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 19 -F 1804 -Q 1 --no-per-base --by /media/kokyriakidis/REDPRO/work/coverage/KONSTANTINOS/target-genome.bed --quantize 0:1:4: /media/kokyriakidis/REDPRO/work/bcbiotx/tmp_0u74h5t/KONSTANTINOS-variant_regions /media/kokyriakidis/REDPRO/work/align/KONSTANTINOS/KONSTANTINOS-sort.bam 
fatal.nim(39)            sysFatal
Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	2124193	19	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
' returned non-zero exit status 1.

```

Any thoughts?

**Comment by brentp** [comment]
can you report your mosdepth version? if that's current, could you share all reads in the bam file with a qname of `A00910:57:HWLFCDSXX:2:1275:24695:34867` ?

**Comment by kokyriakidis** [comment]
It is mosdepth 0.2.6. Sorry for my poor bioinformatics skills but can you send me the command I need to use?

**Comment by brentp** [comment]
```
samtools view -h $bam | grep -Pw '^@|A00910:57:HWLFCDSXX:2:1275:24695:34867` > test.sam
```
should give me a usable value.

**Comment by kokyriakidis** [comment]
There you are


[test.zip](https://github.com/brentp/mosdepth/files/3980050/test.zip)

**Comment by brentp** [comment]
hi, I have pushed a fix for this that will be out next release. It was a bad assertion. Assertions should be compiled out of any production code running mosdepth (which is why  I never noticed this problem before). Are you compiling mosdepth on your own?

You can get around this by adding --fast-mode to the command-line options.

**Comment by kokyriakidis** [comment]
I am using it in bcbio so it is an automated run. Do you know how can I make it run?

**Comment by brentp** [comment]
you can try this (if you have write permission):
```
m=$(which mosdepth)
wget -O $m https://github.com/brentp/mosdepth/releases/download/v0.2.6/mosdepth
chmod +x $m
```

or you can download that binary to e.g. ~/bin/ and then `export PATH=~/bin/:$PATH`

**Comment by kokyriakidis** [comment]
It works now! Thank you very much!
